### ISSUE TITLE
List symbols cannot be displayed when the embedded source text is an article type

### ISSUE THREAD

**Issue by Yubuxin** [efemkay/obsidian-listive-theme#2]
Thank you for this amazing theme! I've always dreamed of implementing a Logseq or Workflowy style in Obsidian, and this theme is very helpful.

But in the process, I ran into a problem: Obsidian is, after all, a document editor, and when you embed a block of document text in a list, the list symbol is hidden, which makes it look a little weird. As shown in the picture below:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/87011715/219624131-9ca5645f-5c6b-4c71-b74e-d187336597c0.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/87011715/219624273-a5ced976-b87b-4b90-bae3-219e9271f47d.png">

Is there any way around this problem? Thank you very much!

**Comment by efemkay** [comment]
hi there. by default the list-embed feature is enabled globally by default. you can disable it via Style Settings
![image](https://user-images.githubusercontent.com/42369515/219817894-fd9b8ebb-88ea-4991-be0a-cde8cd6295b1.png)

but of course with this disabled, any list embed you want to have seamless look, you need to add `|list-embed` in the link e.g. `[[filename|list-embed]]`

**Comment by Yubuxin** [comment]
@efemkay Thanks for reply, got it, but still looking forward to being able to work with both formats by default and not having to manually enter the specified information. (but that's fine now, thanks again! )

**Comment by Yubuxin** [comment]
> hi there. by default the list-embed feature is enabled globally by default. you can disable it via Style Settings ![image](https://user-images.githubusercontent.com/42369515/219817894-fd9b8ebb-88ea-4991-be0a-cde8cd6295b1.png)
> 
> but of course with this disabled, any list embed you want to have seamless look, you need to add `|list-embed` in the link e.g. `[[filename|list-embed]]`

I tried to do it the way you said for a while. Here's a new suggestion: is it possible to implement a syntax that avoids rendering without list-symbol, such as `[[filename|non-embed]]`, with the theme enabled generally?

Since in my practice, embedding document blocks is much less common than embedding list blocks, I thought it might be more useful to include a syntax that avoids rendering without list-symbol.

Anyway, thanks again for making such an excellent theme.

**Comment by Yubuxin** [comment]
@efemkay I tried to do it the way you said for a while. Here's a new suggestion: is it possible to implement a syntax that avoids rendering without list-symbol, such as `[[filename|non-embed]]`, with the theme enabled generally?

Since in my practice, embedding document blocks is much less common than embedding list blocks, I thought it might be more useful to include a syntax that avoids rendering without list-symbol.

Anyway, thanks again for making such an excellent theme.

**Comment by efemkay** [comment]
That's a good suggestion. I'll put it in my enhancement list. Thanks!

**Comment by efemkay** [comment]
@Yubuxin with [v0.4.1](https://github.com/efemkay/obsidian-listive-theme/releases/tag/0.4.1) release i've made some adjustment to List Embed.
- It's disabled by default
- if enabled, the non-list block embed won't be affected by my adjustment for bullet list (see screenshot below)

![image](https://github.com/efemkay/obsidian-listive-theme/assets/42369515/63cc26bd-5cb5-4ca4-ba56-bc815f57a8d0)

> for you to test
> ```md
> - #### non list block (1) without alt, (2) with alt, and (3) replicated, not an embed
>     - ![[#^2374b2]]
>     - ![[#^2374b2|inline-embed]]
>     - **Replicated non list block**. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> 
> **This is a non list block**. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ^2374b2
```
